version: '3.9'

services:
  postgres:
    build:
     context: .
     dockerfile: Database.Dockerfile
    image: postgres:16
    environment:
      POSTGRES_DB : JobApp
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : test
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database-postgresql:/var/lib/postgresql/data
    

  my-aspnet-app:
    build:
      context: ../JobApplicationAPI
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - postgres
volumes:
  database-postgresql: